### ISSUE TITLE
[BUG]: Inference error: 'Sizes of tensors must match except in dimension 1'

### ISSUE THREAD

**Issue by bruesba** [CosmiQ/solaris#221]
Hi,

I fine-tuned XDXD's model on my own dataset (configured for training with pretrained weights set to true) and am now trying to infer on an image that was also in the training set just to see how it'll come out. However this error is thrown upon doing so: 
> Traceback (most recent call last):
  File "c:/Users/blue/Documents/solaris/xdxd_inference.py", line 9, in <module>
    inferer(inference_data)
  File "c:\Users\blue\Documents\solaris\solaris\nets\infer.py", line 87, in __call__
    subarr_preds = self.model(inf_input)
  File "C:\Users\blue\Miniconda3\envs\solaris\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\Users\blue\Documents\solaris\solaris\nets\zoo\xdxd_sn4.py", line 48, in forward
    dec5 = self.dec5(torch.cat([center, conv5], 1))
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 31 and 30 in dimension 2 at C:/w/1/s/tmp_conda_3.6_035809/conda/conda-bld/pytorch_1556683229598/work/aten/src\THC/generic/THCTensorMath.cu:71

Oddly, inference _is_ successful on images which were not in the training dataset, and which have a different size. Therefore this doesn't strike me as a bug but rather as an oversight regarding settings on my part. Any idea why the error could be thrown? Both training and test images are (500, 500, 3) and are normalised the same way. Random crops are taken from the training images (320, 320) during augmentation but when inferring from non-training data (480, 480, 3), this is not problematic. The only differences in the configuration file are `train`, `infer` and `pretrained` when used for training and testing.
[yaaml.zip](https://github.com/CosmiQ/solaris/files/3460928/yaaml.zip)

**Comment by nrweir** [comment]
@bruesba,

Yeah, that's strange. It's particularly weird that it doesn't throw an error until the `dec5` layer of the model, which is the first up-convolution after the encoder. If I had to guess, I'd say that the `InferenceTiler` is probably generating differently shaped outputs than the `TorchDataset` used during training for some reason, even though the inputs are the same. The [docs](https://solaris.readthedocs.io/en/latest/api/nets.html#module-solaris.nets.datagen) are currently a little bit thin on the InferenceTiler, but the [source](https://solaris.readthedocs.io/en/latest/_modules/solaris/nets/datagen.html#InferenceTiler) might help. My suggestion would be to look directly at what's generated by the `InferenceTiler` vs the `TorchDataset` and see if it clarifies how they're different.

**Comment by nrweir** [comment]
@bruesba did you happen to figure out what was going on here? I want to try to track this down before releasing 0.2.0.

**Comment by bruesba** [comment]
I'm afraid not but it could well have been an oversight on my part! (a colleague ran into a similar error when they ran Trainer on a .yml configured for inference, if I recall correctly.) Will let you know if I run into it again. Thanks for your communication!

**Comment by nrweir** [comment]
OK no worries, thanks for the response!

**Comment by andresfchamorro** [comment]
Hi there,

I'm running into the exact same error, using XDXD's algorithm on a different dataset.
Let me know if you've found other advise on how to debug this. 

Thanks

---> 48         dec5 = self.dec5(torch.cat([center, conv5], 1))
     49         dec4 = self.dec4(torch.cat([dec5, conv4], 1))
     50         dec3 = self.dec3(torch.cat([dec4, conv3], 1))

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 30 and 31 in dimension 2 at ..\aten\src\TH/generic/THTensor.cpp:711

**Comment by nrweir** [comment]
Hi @andresfchamorro,

Thanks for letting us know! Can you provide any more context on your use case? (Is it an open dataset by any chance? What did you change in the config file? Etc.)

If the dataset is open or you can provide me with some of the data, and if you can provide me a minimal example to reproduce the error I'm happy to try to help troubleshoot. (This goes for you too @bruesba)

Thanks!
Nick

**Comment by andresfchamorro** [comment]
@nrweir Thanks for the response.

I did not change much in the config file, except for some data specs and the image_type to 8-bit. I also tried with z-score (even though I haven't normalized the inputs) and got the same error. 

It is not an open dataset, but I can send you a small subset that still produces the same error. Send me an email at afche18@gmail.com and we can set that up.

**Comment by nrweir** [comment]
Hey @andresfchamorro and @bruesba,

I _might_ have figured out what's going on here. 

__Short answer:__ inference using XD_XD's model requires the x and y dimensions of your data to be 512x512. If you're re-training, the input width and height must still be divisible by 32.

__Long version:__
@andresfchamorro, in the yml file in the data you sent me, you specify 500x500 tiles in `data_specs[width]` and `data_specs[height]`. XD_XD's model that you two are both (?) using has a VGG16 encoder. This encoder does five rounds of two-fold downsampling of the x and y dimensions. Because downsampling 500 two-fold five times doesn't yield an integer (that is, 500/(2^5) = 15.625), the encoder output ends up being 15 across, but the decoder dimensionality rounds up, expecting 16.

@andresfchamorro if you're locked to using 500x500 tiles, I'd recommend still setting the input dimensions to 512x512 and using the albumentations `Pad` augmenter during data ingestion. If not, just switch to 512x512.

@bruesba, does this look like it could be causing your problems too?

**Comment by KPGeo** [comment]
Thanks for the advice and great library! It is awesome. 

My two cents: 
I repeatedly ran into this error at inference. It is not very clear, but in my case it would get thrown for one of 4 reasons; 
1) the list csv in the yml is not formatted as expected,
2) the csv is not referencing the correct data, 
3) the yml is not referencing the correct csv, 
4) the size of the input COG was not chipped into a size also divisible by 32.

After running through that checklist, it should run.  It might help to have an error statement reminding users to "verify that inputs (CSV, YML, tensors) are formatted as expected."

**Comment by nrweir** [comment]
@KPGeo thanks for this, very good to know. We can make those changes unless you want to put a PR in.
