### ISSUE TITLE
[FEATURE]: Support for HTTPS in reference CSVs

### ISSUE THREAD

**Issue by bruesba** [CosmiQ/solaris#238]
Could support for reference to online images also be implemented? Upon attempting to infer from [https://geodata.nationaalgeoregister.nl/luchtfoto/rgb/wms?request=GetMap&service=WMS&version=1.3.0&layers=2018_ortho25&styles=&width=960&height=960&format=image/png&crs=EPSG:28992&bbox=112682.655, 564705.18, 112762.655, 564785.18] (spaces are part of url), the following is raised, whereas the same image is processed fine when it's locally saved: 
`Traceback (most recent call last):
  File "c:/Users/blue/Documents/solaris/rieten-inference.py", line 10, in <module>
    inferer(inference_data)
  File "c:\Users\blue\Documents\solaris\solaris\nets\infer.py", line 64, in __call__
    src_im_height, src_im_width) = inf_tiler(im_path)
  File "c:\Users\blue\Documents\solaris\solaris\nets\datagen.py", line 261, in __call__
    im = imread(im)
  File "c:\Users\blue\Documents\solaris\solaris\utils\io.py", line 52, in imread
    im_arr = skimage.io.imread(path)
  File "C:\Users\blue\Miniconda3\envs\solaris\lib\site-packages\skimage\io\_io.py", line 60, in imread
    with file_or_url_context(fname) as fname:
  File "C:\Users\blue\Miniconda3\envs\solaris\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\blue\Miniconda3\envs\solaris\lib\site-packages\skimage\io\util.py", line 27, in file_or_url_context
    u = urllib.request.urlopen(resource_name)
  File "C:\Users\blue\Miniconda3\envs\solaris\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\blue\Miniconda3\envs\solaris\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\blue\Miniconda3\envs\solaris\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\blue\Miniconda3\envs\solaris\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\blue\Miniconda3\envs\solaris\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\blue\Miniconda3\envs\solaris\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500:`

Best,
Blue

**Comment by nrweir** [comment]
Yeah definitely a good idea, particularly as things like STAC catalogs become more prevalent. I'll add it to the list.
