### ISSUE TITLE
[BUG]: PILLOW_VERSION

### ISSUE THREAD

**Issue by EugeneDG** [CosmiQ/solaris#326]
_Thank you for helping us improve `solaris`!_

## Summary of the bug
There appears to be an issue with PIL version

## Steps to reproduce the bug

By following the installation instructions you get the following error:

```
  conda env create -n solaris -f environment-gpu.yml
  conda activate solaris
  pip install .
  solaris_run_ml --help

...
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (anaconda3/envs/solaris/lib/python3.7/site-packages/PIL/__init__.py)
```

Installing Pillow 6.1 appears to resolve the issue:
```
pip install Pillow==6.1
solaris_run_ml --help

usage: solaris_run_ml [-h] --config CONFIG

Run a Solaris ML pipeline based on a config YAML

optional arguments:
  -h, --help            show this help message and exit
  --config CONFIG, -c CONFIG
                        Full path to a YAML-formatted config file specifying
                        parameters for model training and/or inference.

```

Same behavior occurred in master and v0.2.0

**Comment by EugeneDG** [comment]
Same issue/solution occurs inside the docker:

```
(solaris) root@2efbb67525ef:/tmp# solaris_run_ml --help
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/opt/conda/envs/solaris/bin/solaris_run_ml", line 5, in <module>
    from solaris.bin.solaris_run_ml import main
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/solaris/__init__.py", line 1, in <module>
    from . import bin, data, eval, nets, raster, tile, utils, vector
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/solaris/data/__init__.py", line 7, in <module>
    from . import coco
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/solaris/data/coco.py", line 1, in <module>
    from ..utils.core import _check_df_load, _check_geom, get_files_recursively
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/solaris/utils/__init__.py", line 1, in <module>
    from . import cli, config, core, geo, io, tile, data
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/solaris/utils/config.py", line 2, in <module>
    from ..nets import zoo
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/solaris/nets/__init__.py", line 6, in <module>
    from . import callbacks, datagen, infer, losses, metrics, model_io
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/solaris/nets/infer.py", line 5, in <module>
    from .model_io import get_model
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/solaris/nets/model_io.py", line 9, in <module>
    from .zoo import model_dict
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/solaris/nets/zoo/__init__.py", line 3, in <module>
    from .xdxd_sn4 import XDXD_SpaceNet4_UNetVGG16
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/solaris/nets/zoo/xdxd_sn4.py", line 4, in <module>
    from torchvision.models import vgg16
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/torchvision/__init__.py", line 4, in <module>
    from torchvision import datasets
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
    from .. import transforms
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/opt/conda/envs/solaris/lib/python3.7/site-packages/PIL/__init__.py)
(solaris) root@2efbb67525ef:/tmp# pip install Pillow==6.1
Collecting Pillow==6.1
  Using cached https://files.pythonhosted.org/packages/a4/da/2bd281c875686230eabc13d20ab590ea617563b0e746abfb0698c4d5b645/Pillow-6.1.0-cp37-cp37m-manylinux1_x86_64.whl
Installing collected packages: Pillow
  Found existing installation: Pillow 7.0.0
    Uninstalling Pillow-7.0.0:
      Successfully uninstalled Pillow-7.0.0
Successfully installed Pillow-6.1.0
(solaris) root@2efbb67525ef:/tmp# solaris_run_ml --help
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
usage: solaris_run_ml [-h] --config CONFIG

Run a Solaris ML pipeline based on a config YAML

optional arguments:
  -h, --help            show this help message and exit
  --config CONFIG, -c CONFIG
                        Full path to a YAML-formatted config file specifying
                        parameters for model training and/or inference.
(solaris) root@2efbb67525ef:/tmp# 


```

**Comment by nrweir** [comment]
This looks like it should be an easy "update the pin in requirements, environment ymls, and setup.py to a version that works" - if you have time to make the change and a PR we'd be forever grateful! If not, we'll try to get to it soon.

**Comment by hugovk** [comment]
There should be a fixed torchvision out this week (https://github.com/pytorch/vision/issues/1712#issuecomment-570286349), in the meantime the fix is to pin `pillow<7`.

**Comment by nrweir** [comment]
Thanks for the heads up @hugovk. In this case I'll probably let users manage it themselves rather than explicitly pin in the repo since it'll be fixed in a few days.

**Comment by nrweir** [comment]
Alright I think this is resolved now - if the error recurs, feel free to re-open.

**Comment by hugovk** [comment]
[torchvision v0.5.0](https://github.com/pytorch/vision/releases/tag/v0.5.0) has been released with the fix:

1. Require `torchvision>=0.5.0`
2. If Pillow was temporarily pinned, remove the pin
