### ISSUE TITLE
[BUG]: IProgress not found. Please update jupyter & ipywidgets

### ISSUE THREAD

**Issue by skyprince999** [CosmiQ/solaris#392]
#359  Summary of the bug

## Steps to reproduce the bug
Please either paste sample code used to generate the buggy behavior below, or provide step-by-step instructions to reproduce the problem.

```
Paste bug-causing code here
```

## Buggy behavior and/or error message
Please describe the buggy behavior and/or paste output here.
```
Paste output here
```

## Environment information
- OS: GNU-Linux (GCP Deep Learning Platform with TF2.1 pre-installed) 
- `solaris` version: 0.3.0
- python version: 3.7.6
- tqdm: 4.48.0 

## Additional context
Hardware: 
N1 4vCPUs, 15GB RAM 
NVidia Tesla T4

I get the above error while running the following notebook 
https://github.com/jshermeyer/solaris_cowc/blob/master/map_vehicles_cowc.ipynb

The error occurs on the following line: 
`trainer = sol.nets.train.Trainer(config)`

It first tries to download the VGG16 pre-trained model and then the Spacenet weights.  

However while downloading the weights I get the above error, on the status bar. from the get_model >> download_model module. 

The same error re-occurred when I was running the [Tiling tutorial](https://solaris.readthedocs.io/en/latest/tutorials/notebooks/api_tiling_tutorial.html)

The error was for the following code block:
`raster_bounds_crs = raster_tiler.tile('/path/to/raster/file/3band/PS-RGB_mosaic_013022223133.tif')`

The error log had the following:
`Exception ignored in: <function tqdm.__del__ at 0x7fe617c33290>
Traceback (most recent call last):
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/tqdm/std.py", line 1087, in __del__
    self.close()
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/tqdm/notebook.py", line 247, in close
    self.sp(bar_style='success')
AttributeError: 'tqdm_notebook' object has no attribute 'sp'`

followed by - 

`ImportError: IProgress not found. Please update jupyter and ipywidgets.......`

**Comment by DavidJohn197749** [comment]
i meet same the error on my juptyer notebook (using docker). i resolve it by changing the notebook dir. if you run jupyter notebook  using root dir, using the --notebook-dir to change the dir may help you.

**Comment by koeglfryderyk** [comment]
Thanks, that worked!

**Comment by PingHGao** [comment]
> i meet same the error on my juptyer notebook (using docker). i resolve it by changing the notebook dir. if you run jupyter notebook using root dir, using the --notebook-dir to change the dir may help you.

Sir, my dir is the `Desktop`. But I meet the same error.

**Comment by ViniMM2** [comment]
> > i meet same the error on my juptyer notebook (using docker). i resolve it by changing the notebook dir. if you run jupyter notebook using root dir, using the --notebook-dir to change the dir may help you.
> 
> Sir, my dir is the `Desktop`. But I meet the same error.
> 
> I solved this by chaging
> 
> ```
> from tqdm.notebook import tqdm as tqdm
> ```
> 
> to
> 
> ```
> from tqdm import tqdm
> ```
> 
> solved this

Thanks for the solution!

**Comment by ViniMM2** [comment]
> > i meet same the error on my juptyer notebook (using docker). i resolve it by changing the notebook dir. if you run jupyter notebook using root dir, using the --notebook-dir to change the dir may help you.
> 
> Sir, my dir is the `Desktop`. But I meet the same error.
> 
> I solved this by chaging
> 
> ```
> from tqdm.notebook import tqdm as tqdm
> ```
> 
> to
> 
> ```
> from tqdm import tqdm
> ```
> 
> solved this

Thanks, PingHGao. Really worked!

**Comment by Aleksandar1932** [comment]
If you are using jupyter-lab, try this: `jupyter nbextension enable --py widgetsnbextension`. Was able to reproduce and fixed issues.

**Comment by AcylSilane** [comment]
> If you are using jupyter-lab, try this: `jupyter nbextension enable --py widgetsnbextension`. Was able to reproduce and fixed issues.

Also needed to `pip install ipywidgets` for this.

**Comment by ZSoumia** [comment]
Reinstalling tqdm solved the issue for me
`conda install -c conda-forge tqdm
`

**Comment by mickeykawai** [comment]
> > > i meet same the error on my juptyer notebook (using docker). i resolve it by changing the notebook dir. if you run jupyter notebook using root dir, using the --notebook-dir to change the dir may help you.
> > 
> > 
> > Sir, my dir is the `Desktop`. But I meet the same error.
> > I solved this by chaging
> > ```
> > from tqdm.notebook import tqdm as tqdm
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```
> > from tqdm import tqdm
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > solved this
> 
> Thanks, PingHGao. Really worked!



> > i meet same the error on my juptyer notebook (using docker). i resolve it by changing the notebook dir. if you run jupyter notebook using root dir, using the --notebook-dir to change the dir may help you.
> 
> Sir, my dir is the `Desktop`. But I meet the same error.
> 
> I solved this by chaging
> 
> ```
> from tqdm.notebook import tqdm as tqdm
> ```
> 
> to
> 
> ```
> from tqdm import tqdm
> ```
> 
> solved this

Thank you, PingHGao! It helped and saved my time very much!
```
python3 --version
Python 3.9.10
# installed at non-standard directory. 

import sys
print("python:", sys.version)
python: 3.9.10 (main, Jan 31 2022, 06:20:15) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

pip3 list | grep -E 'jupyter|ipywidgets|tqdm'
ipywidgets           7.6.5
jupyter              1.0.0
jupyter-client       7.1.2
jupyter-console      6.4.0
jupyter-core         4.9.1
jupyterlab-pygments  0.1.2
jupyterlab-widgets   1.0.2
tqdm                 4.62.3
```

**Comment by scign** [comment]
> > i meet same the error on my juptyer notebook (using docker). i resolve it by changing the notebook dir. if you run jupyter notebook using root dir, using the --notebook-dir to change the dir may help you.
> 
> Sir, my dir is the `Desktop`. But I meet the same error.
> 
> I solved this by chaging
> 
> ```
> from tqdm.notebook import tqdm as tqdm
> ```
> 
> to
> 
> ```
> from tqdm import tqdm
> ```
> 
> solved this

A more flexible way could be:
```
try:
    import IProgress
    from tqdm.notebook import tqdm
except ImportError:
    from tqdm import tqdm
```
This will import the widget version of tqdm if widgets are supported, and the console version if not.

**Comment by ZhuoHan1998** [comment]
I tried to install ipywigdets by 'pip install ipywidgets', and it works for me. No such errors since then.

**Comment by MewmewWho** [comment]
I'm building my own Docker image from Jupyter's minimal-notebook image. With a 'mamba install ipywidgets', I casafely import tqdm classes from tqdm.notebook.

**Comment by ghost** [comment]
I encountered the same issue:
![image](https://github.com/CosmiQ/solaris/assets/87641643/c9a7ce3b-d669-4dc3-b07f-ab68cd407c0d)

with the following packages:
```
python3 jupyter.py --version
IPython          : 8.18.1
ipykernel        : 6.27.1
ipywidgets       : not installed
jupyter_client   : 8.6.0
jupyter_core     : 5.5.0
jupyter_server   : 2.12.1
jupyterlab       : 4.0.9
nbclient         : 0.9.0
nbconvert        : 7.12.0
nbformat         : 5.9.2
notebook         : not installed
qtconsole        : not installed
traitlets        : 5.14.0
```
The following packages are not installed directly with `pip3 install jupyterlab`

```
ipywidgets       : not installed
notebook         : not installed
qtconsole        : not installed
```
However, after installing these packages, the issue is resolved:
![image](https://github.com/CosmiQ/solaris/assets/87641643/8a47423d-3ebc-4e4a-a72a-50b9d0cb3d10)

`pip3 install notebook ipywidgets  qtconsole`

And here are the installed versions:
```
IPython          : 8.18.1
ipykernel        : 6.27.1
ipywidgets       : 8.1.1
jupyter_client   : 8.6.0
jupyter_core     : 5.5.1
jupyter_server   : 2.12.1
jupyterlab       : 4.0.9
nbclient         : 0.9.0
nbconvert        : 7.13.0
nbformat         : 5.9.2
notebook         : 7.0.6
qtconsole        : 5.5.1
traitlets        : 5.14.0

```

**Comment by GigleGig** [comment]
> I encountered the same issue: ![image](https://private-user-images.githubusercontent.com/87641643/291945180-c9a7ce3b-d669-4dc3-b07f-ab68cd407c0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MDMwMTksIm5iZiI6MTcxNDQwMjcxOSwicGF0aCI6Ii84NzY0MTY0My8yOTE5NDUxODAtYzlhN2NlM2ItZDY2OS00ZGMzLWIwN2YtYWI2OGNkNDA3YzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE0NTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NTJkOTk1OWU2NmY4YTQ4MDBhMzhjZGU2OTUxYTI5YjQ3MTliYzZmOGVjODY1OGVmNzk2NjJkYTQ4YWU4NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S1QzywKLlOiiyawpoB1UOUs-AiB9NK_kVUZA_xynwkE)
> 
> with the following packages:
> 
> ```
> python3 jupyter.py --version
> IPython          : 8.18.1
> ipykernel        : 6.27.1
> ipywidgets       : not installed
> jupyter_client   : 8.6.0
> jupyter_core     : 5.5.0
> jupyter_server   : 2.12.1
> jupyterlab       : 4.0.9
> nbclient         : 0.9.0
> nbconvert        : 7.12.0
> nbformat         : 5.9.2
> notebook         : not installed
> qtconsole        : not installed
> traitlets        : 5.14.0
> ```
> 
> The following packages are not installed directly with `pip3 install jupyterlab`
> 
> ```
> ipywidgets       : not installed
> notebook         : not installed
> qtconsole        : not installed
> ```
> 
> However, after installing these packages, the issue is resolved: ![image](https://private-user-images.githubusercontent.com/87641643/291946869-8a47423d-3ebc-4e4a-a72a-50b9d0cb3d10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MDMwMTksIm5iZiI6MTcxNDQwMjcxOSwicGF0aCI6Ii84NzY0MTY0My8yOTE5NDY4NjktOGE0NzQyM2QtM2ViYy00ZTRhLWE3MmEtNTBiOWQwY2IzZDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE0NTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNDliMTdlOTdmNzY0MzcxNjExYTgwYmZjMTA4MTJmMGIxYjA2YmEyZWUzNWE0YjRhNjIwMjM5ZTA4YzkxZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XYIJwgNs1OFS3IxnO63uprNfxhGHbcCEjnzBoN1zHwU)
> 
> `pip3 install notebook ipywidgets qtconsole`
> 
> And here are the installed versions:
> 
> ```
> IPython          : 8.18.1
> ipykernel        : 6.27.1
> ipywidgets       : 8.1.1
> jupyter_client   : 8.6.0
> jupyter_core     : 5.5.1
> jupyter_server   : 2.12.1
> jupyterlab       : 4.0.9
> nbclient         : 0.9.0
> nbconvert        : 7.13.0
> nbformat         : 5.9.2
> notebook         : 7.0.6
> qtconsole        : 5.5.1
> traitlets        : 5.14.0
> ```

thanks bro, problem solved.

**Comment by Irratzo** [comment]
@gaopinghai 's [solution](https://github.com/CosmiQ/solaris/issues/392#issuecomment-759238485) (don't bother with `tqdm.notebook` and just always use `from tqdm import tqdm`) resolved the original issue in notebooks for me as well. But the output is not as nice anymore. If you want to see the nicely rendered tqdm progress bar in notebooks instead, go with the `pip install ipywidgets` solution instead, as others have pointed out, and keep your original import. That worked for me.
